// Data 3 aplikasi daftar tugas. `halaman` = halaman dalam yang bisa dicoba langsung.
export const templates = [
  {
    name: 'Hari Ini',
    berkas: 'hari-ini',
    tagline: 'Satu daftar untuk satu hari',
    description: 'Yang selesai pindah ke rekap besoknya, yang belum ikut terbawa. Ketik "Telepon klien 14.00 !" dan jam serta prioritasnya langsung terbaca.',
    image: '/images/todo/hari-ini.webp',
    url: 'https://todo-classic.vercel.app',
    fitur: ['Jam & prioritas dibaca dari ketikan', 'Tugas belum selesai terbawa ke esok hari', 'Rekap 7 hari dengan streak'],
    cocok: 'daftar harian & kebiasaan',
    halaman: [['/rekap', 'Rekap 7 hari'], ['/panduan', 'Panduan']],
  },
  {
    name: 'Lajur',
    berkas: 'lajur',
    tagline: 'Papan kanban dengan batas WIP',
    description: 'Tiga lajur — Antre, Dikerjakan, Selesai — dengan batas tiga kartu yang dikerjakan sekaligus. Setiap kartu mencatat kapan mulai dan selesai.',
    image: '/images/todo/lajur.webp',
    url: 'https://todo-kanban-one.vercel.app',
    fitur: ['Seret kartu — mouse, sentuh, atau papan ketik', 'Checklist, tenggat, dan label di tiap kartu', 'Statistik lead time & cycle time'],
    cocok: 'proyek & tim kecil',
    halaman: [['/statistik', 'Statistik'], ['/arsip', 'Arsip']],
  },
  {
    name: 'Tuntas',
    berkas: 'tuntas',
    tagline: 'Pengelola tugas dengan kalender',
    description: 'Prioritas, tenggat yang dibaca relatif ("Besok", "Terlambat 2 hari"), label, dan kalender bulanan — untuk urusan kerja dan rumah sekaligus.',
    image: '/images/todo/tuntas.webp',
    url: 'https://todo-manager-ivory-seven.vercel.app',
    fitur: ['Ringkasan yang sekaligus menyaring', 'Kalender bulanan per tanggal tenggat', 'Ganti nama label untuk semua tugas'],
    cocok: 'kerja & urusan rumah',
    halaman: [['/kalender', 'Kalender'], ['/label', 'Label']],
  },
];
